disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- nesting
- identifier_name
- type_name
- vertical_parameter_alignment

force_cast: warning
force_try: warning

cyclomatic_complexity: 15
function_body_length: 50
line_length: 175
file_length: 500

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- fastlane
- Frameworks
- ATParseIncrementalStore Example iOS
